# Generated by Django 5.0.6 on 2024-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contentProject",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="imageProject",
            field=models.ImageField(null=True, upload_to="project_images/"),
        ),
    ]
