# Generated by Django 5.0.6 on 2024-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0005_alter_project_imageproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="imageProject",
            field=models.ImageField(null=True, upload_to="portafolio_images/"),
        ),
    ]
