# Generated by Django 5.0.6 on 2024-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0006_project_price_alter_project_imageproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contentProject",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
